### PR TITLE
Added Molecule tests

### PR DESCRIPTION
**Pull request by orenbm**
#### What does this PR do?
Adding molecule test to Ansible

#### Where should the reviewer start?
molecule

#### How should this be manually tested?
run test.sh

#### What are the relevant tickets?
#25 

#### Reviewers
@jvanderhoof 
@jeniaSakirko 
@nessiCyber 
@dustinmm80

### CODE REVIEW

**Comment by jvanderhoof** [comment]
When I run:
```sh
$ ./test.sh
```
I get the following error in the bash output:
```sh
-----
Conjurizing the target container with Ansible
-----
./test.sh: line 69: molecule: command not found
-----
Retrieving secret with ansible-master identity
-----
./test.sh: line 80: molecule: command not found
-----
-----
Retrieving secret with conjurized target identity
-----
./test.sh: line 93: molecule: command not found
-----
Removing demo environment
-----
Stopping ansibleroleconjur_client_1 ... done
Stopping ansibleroleconjur_conjur_1 ... done
Stopping ansibleroleconjur_postgres_1 ... done
Removing ansibleroleconjur_client_run_2 ... done
Removing ansibleroleconjur_client_run_1 ... done
Removing ansibleroleconjur_client_1 ... done
Removing ansibleroleconjur_conjur_1 ... done
Removing ansibleroleconjur_postgres_1 ... done
Removing network ansibleroleconjur_default
```

**Comment by jvanderhoof** [comment]
Also looks like there are some merge conflicts on this branch.

**Comment by orenbm** [comment]
Yes, well you need molecule installed in your machine (or in any machine that will run the tests) for running molecule tests. Is this too much?

**Comment by orenbm** [comment]
Regarding the conflicts, that's because there were some changes in the previous days that were merged to master before this. Once this PR will be approved I'll fix the conflicts and merge to master

**Comment by jvanderhoof** [comment]
Tests still don't look like they are passing after installing `molecule`.  I'm seeing the following:
```sh
Retrieving secret with conjurized target identity
-----
--> Test matrix

└── retrieve-secret-in-remote
    ├── destroy
    ├── create
    ├── converge
    ├── verify
    └── destroy
--> Scenario: 'retrieve-secret-in-remote'
--> Action: 'destroy'

    PLAY [Destroy] *****************************************************************

    TASK [Destroy molecule instance(s)] ********************************************
    failed: [localhost] (item=(censored due to no_log)) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1


ERROR:
-----
```

**Comment by jvanderhoof** [comment]
Here's `pip install`, test run, and python version:
```sh
➜  ansible-role-conjur git:(molecule_tests) ✗ pip install molecule
Requirement already satisfied: molecule in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: click-completion==0.2.1 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: ansible-lint==3.4.13 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: anyconfig==0.9.1 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: cookiecutter==1.5.1 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: testinfra==1.6.3 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: tree-format==0.1.1 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: click==6.7 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: psutil==5.2.2 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: flake8==3.3.0 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: colorama==0.3.7 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: PyYAML==3.12 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: pbr==3.0.1 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: tabulate==0.7.7 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: marshmallow==2.13.5 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: python-gilt==1.1.0 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: Jinja2==2.9.6 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: yamllint==1.8.1 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: pexpect==4.2.1 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: sh==1.12.14 in /usr/local/lib/python2.7/site-packages (from molecule)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from click-completion==0.2.1->molecule)
Requirement already satisfied: ansible in /usr/local/lib/python2.7/site-packages (from ansible-lint==3.4.13->molecule)
Requirement already satisfied: binaryornot>=0.2.0 in /usr/local/lib/python2.7/site-packages (from cookiecutter==1.5.1->molecule)
Requirement already satisfied: jinja2-time>=0.1.0 in /usr/local/lib/python2.7/site-packages (from cookiecutter==1.5.1->molecule)
Requirement already satisfied: poyo>=0.1.0 in /usr/local/lib/python2.7/site-packages (from cookiecutter==1.5.1->molecule)
Requirement already satisfied: future>=0.15.2 in /usr/local/lib/python2.7/site-packages (from cookiecutter==1.5.1->molecule)
Requirement already satisfied: whichcraft>=0.4.0 in /usr/local/lib/python2.7/site-packages (from cookiecutter==1.5.1->molecule)
Requirement already satisfied: pytest!=3.0.2 in /usr/local/lib/python2.7/site-packages (from testinfra==1.6.3->molecule)
Requirement already satisfied: enum34; python_version < "3.4" in /usr/local/lib/python2.7/site-packages (from flake8==3.3.0->molecule)
Requirement already satisfied: configparser; python_version < "3.2" in /usr/local/lib/python2.7/site-packages (from flake8==3.3.0->molecule)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /usr/local/lib/python2.7/site-packages (from flake8==3.3.0->molecule)
Requirement already satisfied: pycodestyle<2.4.0,>=2.0.0 in /usr/local/lib/python2.7/site-packages (from flake8==3.3.0->molecule)
Requirement already satisfied: pyflakes<1.6.0,>=1.5.0 in /usr/local/lib/python2.7/site-packages (from flake8==3.3.0->molecule)
Requirement already satisfied: git-url-parse in /usr/local/lib/python2.7/site-packages (from python-gilt==1.1.0->molecule)
Requirement already satisfied: fasteners in /usr/local/lib/python2.7/site-packages (from python-gilt==1.1.0->molecule)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/site-packages (from Jinja2==2.9.6->molecule)
Requirement already satisfied: pathspec>=0.5.3 in /usr/local/lib/python2.7/site-packages (from yamllint==1.8.1->molecule)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python2.7/site-packages (from pexpect==4.2.1->molecule)
Requirement already satisfied: paramiko in /usr/local/lib/python2.7/site-packages (from ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: pycrypto>=2.6 in /usr/local/lib/python2.7/site-packages (from ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: chardet>=3.0.2 in /usr/local/lib/python2.7/site-packages (from binaryornot>=0.2.0->cookiecutter==1.5.1->molecule)
Requirement already satisfied: arrow in /usr/local/lib/python2.7/site-packages (from jinja2-time>=0.1.0->cookiecutter==1.5.1->molecule)
Requirement already satisfied: py>=1.4.33 in /usr/local/lib/python2.7/site-packages (from pytest!=3.0.2->testinfra==1.6.3->molecule)
Requirement already satisfied: monotonic>=0.1 in /usr/local/lib/python2.7/site-packages (from fasteners->python-gilt==1.1.0->molecule)
Requirement already satisfied: cryptography>=1.1 in /usr/local/lib/python2.7/site-packages (from paramiko->ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python2.7/site-packages (from paramiko->ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python2.7/site-packages (from paramiko->ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python2.7/site-packages (from paramiko->ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/site-packages (from arrow->jinja2-time>=0.1.0->cookiecutter==1.5.1->molecule)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: cffi>=1.7 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: ipaddress in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible->ansible-lint==3.4.13->molecule)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/site-packages (from cffi>=1.7->cryptography>=1.1->paramiko->ansible->ansible-lint==3.4.13->molecule)
➜  ansible-role-conjur git:(molecule_tests) ✗ ./test.sh
-----
----------
---------------
Starting Ansible demo for Conjur
---------------
----------
-----
Creating demo environment
-----
Pulling postgres (postgres:9.3)...
9.3: Pulling from library/postgres
Digest: sha256:92a4f5e1e5ee5d2da6b0dc24622affb1435acf7ce48ee471b3215d26eb82fe90
Status: Image is up to date for postgres:9.3
Pulling conjur (cyberark/conjur:0.1.0-stable)...
0.1.0-stable: Pulling from cyberark/conjur
Digest: sha256:9c881f63c256aae6032c3dfdc72020387d6ebc93177fd2aa43273e9345776a10
Status: Image is up to date for cyberark/conjur:0.1.0-stable
Pulling client (conjurinc/cli5:latest)...
latest: Pulling from conjurinc/cli5
Digest: sha256:d7e2cefd664a847f4a2d28eb843b9630ca633727b6de0f0cc3d71fa0f6d74b76
Status: Image is up to date for conjurinc/cli5:latest
Creating network "ansibleroleconjur_default" with the default driver
Creating ansibleroleconjur_postgres_1
Creating ansibleroleconjur_conjur_1
Creating ansibleroleconjur_client_1
-----
Waiting for conjur server to be healthy
.
.
.
.
.
server is up
-----
Creating Conjur host factory token
-----
Loaded policy 'root'
{
  "created_roles": {
    "cucumber:host:ansible/ansible-master": {
      "id": "cucumber:host:ansible/ansible-master",
      "api_key": "2x956z83bdvxnc1vqmx7f3s2pjar3bkd6y3rd6v5k335ywefd3x14m"
    },
    "cucumber:host:ansible/ansible-custom-target": {
      "id": "cucumber:host:ansible/ansible-custom-target",
      "api_key": "djmxv9kkqje212c2zx37181yz345r4w13drsj4e1914s8zdqr05s"
    }
  },
  "version": 1
}
Value added
Value added
Value added
-----
Conjurizing the target container with Ansible
-----
--> Test matrix

└── configure-conjur-identity
    ├── destroy
    ├── create
    ├── converge
    ├── verify
    └── destroy
--> Scenario: 'configure-conjur-identity'
--> Action: 'destroy'

    PLAY [Destroy] *****************************************************************

    TASK [Destroy molecule instance(s)] ********************************************
    failed: [localhost] (item=(censored due to no_log)) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1


ERROR:
-----
Retrieving secret with ansible-master identity
-----
--> Test matrix

└── retrieve-secret-in-master
    ├── destroy
    ├── create
    ├── converge
    ├── verify
    └── destroy
--> Scenario: 'retrieve-secret-in-master'
--> Action: 'destroy'

    PLAY [Destroy] *****************************************************************

    TASK [Destroy molecule instance(s)] ********************************************
    failed: [localhost] (item=(censored due to no_log)) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1


ERROR:
-----
-----
Retrieving secret with conjurized target identity
-----
--> Test matrix

└── retrieve-secret-in-remote
    ├── destroy
    ├── create
    ├── converge
    ├── verify
    └── destroy
--> Scenario: 'retrieve-secret-in-remote'
--> Action: 'destroy'

    PLAY [Destroy] *****************************************************************

    TASK [Destroy molecule instance(s)] ********************************************
    failed: [localhost] (item=(censored due to no_log)) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1


ERROR:
-----
Removing demo environment
-----
Stopping ansibleroleconjur_client_1 ... done
Stopping ansibleroleconjur_conjur_1 ... done
Stopping ansibleroleconjur_postgres_1 ... done
Removing ansibleroleconjur_client_run_2 ... done
Removing ansibleroleconjur_client_run_1 ... done
Removing ansibleroleconjur_client_1 ... done
Removing ansibleroleconjur_conjur_1 ... done
Removing ansibleroleconjur_postgres_1 ... done
Removing network ansibleroleconjur_default
p%                                                                                                                                                                                                     ➜  ansible-role-conjur git:(molecule_tests) ✗ python --version
Python 2.7.13
```

**Pull request merged**
